In [4]:
import numpy as np
import torch
import csv
import cv2
import unittest
import sys
import os
import pandas
import pandas as pd
import shutil
import glob
import pickle
import albumentations
from albumentations import augmentations
from enum import Enum
from skimage import data
from typing import Iterable, Tuple, List, Union, Set, Any, Dict, Optional, Any, Callable, Sized
from torch.utils.tensorboard import SummaryWriter
import torch.utils
import torch.utils.data
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
"""import elements.common"""
NoneType = type(None)
"""from elements.common.utils import get_logger
logger = get_logger('notebook_logs')"""
import csv
import matplotlib.pyplot as plt
from IPython.display import display, clear_output
import time


In [19]:
# You can copy this code to your personal pipeline project or execute it here.
def swap(coords: np.ndarray):
    """
    This method will flip the x and y coordinates in the coords array.

    :param coords: A numpy array of bounding box coordinates with shape [n,5] in format:
        ::

            [[x11, y11, x12, y12, classid1],
             [x21, y21, x22, y22, classid2],
             ...
             [xn1, yn1, xn2, yn2, classid3]]

    :return: The new numpy array where the x and y coordinates are flipped.

    **This method is part of a series of debugging exercises.**
    **Each Python method of this series contains bug that needs to be found.**

    | ``1   Can you spot the obvious error?``
    | ``2   After fixing the obvious error it is still wrong, how can this be fixed?``

    >>> import numpy as np
    >>> coords = np.array([[10, 5, 15, 6, 0],
    ...                    [11, 3, 13, 6, 0],
    ...                    [5, 3, 13, 6, 1],
    ...                    [4, 4, 13, 6, 1],
    ...                    [6, 5, 13, 16, 1]])
    >>> swapped_coords = swap(coords)

    The example demonstrates the issue. The returned swapped_coords are expected to have swapped
    x and y coordinates in each of the rows.
    """
    coords_copy = coords.copy()
    coords[:, 0], coords[:, 1], coords[:, 2], coords[:, 3] = coords_copy[:, 1], coords_copy[:, 0],coords_copy[:, 3], coords_copy[:, 2]
    return coords

In [21]:
coords = np.array([[10, 5, 15, 6, 0],
                   [11, 3, 13, 6, 0],
                   [5, 3, 13, 6, 1],
                   [4, 4, 13, 6, 1],
                   [6, 5, 13, 16, 1]])
swapped_coords = swap(coords)
print(swapped_coords)

[[ 5 10  6 15  0]
 [ 3 11  6 13  0]
 [ 3  5  6 13  1]
 [ 4  4  6 13  1]
 [ 5  6 16 13  1]]


The bug this code is when x11 = y11, the value of x11 has changed. For this reason when we want to set the value of the y11 equal to the x11, the value of x11 is same with y11. For fixing this bug before flip the x and y coordinates we can make copy of coords list and use of the copy for fliping;